-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.produtos;

CREATE TABLE IF NOT EXISTS public.produtos
(
    id serial NOT NULL,
    categorias_id integer NOT NULL,
    unidades_medida_id character varying(3),
    marca_id integer,
    ncm_id character varying(8),
    status_id integer,
    gtin character varying(14) NOT NULL,
    cest character varying(7),
    ex_tipi character varying(3),
    referencia character varying(20),
    descricao character varying(80) NOT NULL,
    preco_custo double precision,
    margem double precision,
    preco_venda double precision,
    data_inclusao date,
    CONSTRAINT produtos_id_pk PRIMARY KEY (id),
    CONSTRAINT referencia_unique UNIQUE (referencia),
    CONSTRAINT gtin_unique UNIQUE (gtin)
);

DROP TABLE IF EXISTS public.produtos_categoria;

CREATE TABLE IF NOT EXISTS public.produtos_categoria
(
    id serial NOT NULL,
    nome character varying(100) NOT NULL,
    codigo character varying(20),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.produtos_classificacao;

CREATE TABLE IF NOT EXISTS public.produtos_classificacao
(
    id character(8) NOT NULL,
    ex_tipi character(3),
    descricao character varying(600) NOT NULL,
    cest character varying(7),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.produtos_unidade_medida;

CREATE TABLE IF NOT EXISTS public.produtos_unidade_medida
(
    id character varying(6) NOT NULL,
    unidade character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.produtos_marca;

CREATE TABLE IF NOT EXISTS public.produtos_marca
(
    id serial NOT NULL,
    descricao character varying(60) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.status_produtos;

CREATE TABLE IF NOT EXISTS public.status_produtos
(
    id serial NOT NULL,
    descricao character varying(60) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT categorias_id_fk FOREIGN KEY (categorias_id)
    REFERENCES public.produtos_categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT unidades_medida_id_fk FOREIGN KEY (unidades_medida_id)
    REFERENCES public.produtos_unidade_medida (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT ncm_id_fk FOREIGN KEY (ncm_id)
    REFERENCES public.produtos_classificacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT status_id_fk FOREIGN KEY (status_id)
    REFERENCES public.status_produtos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.produtos
    ADD CONSTRAINT marca_id_fk FOREIGN KEY (marca_id)
    REFERENCES public.produtos_marca (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;